# Generated by Django 4.0.5 on 2022-07-04 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emai_address',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='nok_emai_address',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='nok_phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
