# Generated by Django 4.0.5 on 2022-07-09 22:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_emai_address_member_nok_emai_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nok_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
